#! /bin/sh

#### Monitor And WorkSpaces  ####
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
xrandr --output eDP1 --mode 1366x768 --rate 60 &

#### BSPWM configuration ####
bspc config border_width                  2
bspc config window_gap                    2
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config active_border_color	      	  "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#### Window Rule ####
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a gnome-calculator state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Gthumb state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a File-roller state=floating

### AutoStart  ###
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar &
nitrogen --restore &
picom -f &
nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst &
copyq &
blueman-applet &
numlockx on &
udiskie -t &
xfce4-power-manager &
redshift -O 4500K &
xsetroot -cursor_name left_ptr &
